--- 
steps: 
  - 
    name: "maven:latest"
    entrypoint: mvn
    args: 
      - install
  - 
    args: 
      - test
    entrypoint: mvn
    name: "maven:latest"
  
  - 
    args: 
      - login
      - "-u"
      - snobrost
      - "-p"
      - xspmxv34
    entrypoint: docker
    name: "docker:latest"
  - 
    args: 
      - build
      - "-t"
      - "snobrost/demojava:latest"
      - "."
    entrypoint: docker
    name: "docker:latest"
  - 
    args: 
      - push
      - "snobrost/demojava:latest"
      - "."
    entrypoint: docker
    name: "docker:latest"
  - 
    args: 
      - build
      - "-t"
      - "snobrost/demojava:latest"
      - "."
    entrypoint: docker
    name: "docker:latest"
  - 
    args: 
      - push
      - "snobrost/demojava:latest"
      - "."
    entrypoint: docker
    name: "docker:latest"

