--- 
steps: 
  - 
    name: "maven:latest"
    entrypoint: mvn
    args: 
      - install
  - 
    args: 
      - test
    entrypoint: mvn
    name: "maven:latest"
 
  - 
    args: 
      - i
    entrypoint: npm
    dir: "./jsproject/"
    name: "node:latest"
  - 
    args: 
      - run
      - build
    entrypoint: npm
    dir: "./jsproject/"
    name: "node:latest"
  - 
    args: 
      - run
      - test
    entrypoint: npm
    dir: "./jsproject/"
    name: "node:latest"
  - 
    args: 
      - login
      - "-u"
      - $_DOCKERLOGIN
      - "-p"
      - $_DOCKERMDP
    entrypoint: docker
    name: "docker:latest"
  - 
    args: 
      - build
      - "-t"
      - "snobrost/demojava:latest"
      - "."
    entrypoint: docker
    name: "docker:latest"
  - 
    args: 
      - push
      - "snobrost/demojava:latest"
    entrypoint: docker
    name: "docker:latest"

  - 
    args: 
      - build
      - "-t"
      - "snobrost/demojavascript:latest"
      - "."
    entrypoint: docker
    dir: "./jsproject/"
    name: "docker:latest"
  - 
    args: 
      - push
      - "snobrost/demojavascript:latest"
    entrypoint: docker
    dir: "./jsproject/"
    name: "docker:latest"
