--- 
steps: 
  - 
    name: "maven:latest"
    entrypoint: mvn
    args: 
      - install
  - 
    args: 
      - test
    entrypoint: mvn
    name: "maven:latest"
  - 
    args: 
      - i
    entrypoint: npm
    name: "node:latest"
  - 
    args: 
      - run
      - build
    entrypoint: npm
    name: "node:latest"
  - 
    args: 
      - run
      - test
    entrypoint: npm
    name: "node:latest"
